create table mvf2002 ( 
	affidavit   varchar(12), 
	name_prefix varchar(5), 
	name_last   varchar(24), 
	name_first  varchar(16), 
	name_middle varchar(16), 
	street      varchar(19), 
	type        varchar(9), 
	pre_dir     varchar(5), 
	house_number   int, 
	house_fraction char(4), 
	apartment_number  varchar(20), 
	zip         varchar(12), 
	precinct    int, 
	portion     int, 
	party       char(5), 
	reg_date    date, 
	Phone       varchar(18), 
	Perm        char(1), 
	military    char(1), 
	gender      char(1), 
	RegType     varchar(23), 
	birth_place varchar(9), 
	birth_date  date, 
	care_of     varchar(40), 
	mail_street varchar(40), 
	mail_city   varchar(38), 
	mail_state  varchar(28), 
	mail_zip    varchar(21), 
	CONG        int, 
	SEN         int, 
	ASSM        int, 
	SUPV        int, 
	BART        char(3), 
	voter_id int 
);

